blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Quick question / discussion
    url: https://getvocalworkspace.slack.com/archives/C096XQURHL6
    about: Not sure? Ask quick questions on Slack before opening an issue
